name: API Validation Framework CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --no-restore --configuration Release

    - name: Run tests
      run: dotnet test --no-build --configuration Release --verbosity normal

    - name: Setup Swashbuckle CLI as local tool
      run: |
        cd ApiValidationFramework
        dotnet new tool-manifest || echo "Tool manifest already exists"
        dotnet tool install Swashbuckle.AspNetCore.Cli --version 9.0.4
        dotnet tool restore

    - name: Generate Swagger JSON
      run: |
        cd ApiValidationFramework
        dotnet swagger tofile --output swagger.json ./bin/Release/net8.0/ApiValidationFramework.dll v1

  docker-build:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (no push)
        run: docker build -f ApiValidationFramework/Dockerfile -t api-validation-test .
